/**
 * InterviewAI Frontend Build Script
 * Injects VITE_API_URL or API_URL environment variable into frontend/config.js
 * Used by Netlify or any static hosting build process.
 */

const fs = require("fs");
const path = require("path");

const rawApiUrl = (
  process.env.VITE_API_URL ||
  process.env.API_URL ||
  process.env.BACKEND_URL ||
  ""
).trim();

// Strip any trailing slashes from the API URL
const apiUrl = rawApiUrl.replace(/\/+$/, "");

const configContent = `// InterviewAI Runtime API Configuration
// Generated by build.js during build step
window.__API_URL__ = ${JSON.stringify(apiUrl)};
`;

const configPath = path.join(__dirname, "frontend", "config.js");

try {
  fs.writeFileSync(configPath, configContent, "utf8");
  if (apiUrl) {
    console.log(`[build] Successfully configured API URL: ${apiUrl}`);
  } else {
    console.log(
      "[build] Notice: No VITE_API_URL or API_URL detected in environment. Configured empty default for dynamic resolution."
    );
  }
} catch (err) {
  console.error("[build] Failed to write frontend/config.js:", err);
  process.exit(1);
}
